infrastructure:
  templates:
    - rendering_engine: codebuild
      settings:
        image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        runtimes:
          nodejs: 16
        provision:
          - echo "PROTON INPUTS == $(cat proton-inputs.json)"
          - npm install
          # Note that these scripts need to be executable, use git add --chmod=+x to achieve this
          - ./cdk_deploy.sh
          - cat proton-outputs.json | ./cdk-to-proton.sh > outputs.json
          - aws proton notify-resource-deployment-status-change --resource-arn $RESOURCE_ARN --status IN_PROGRESS --outputs file://./outputs.json
        deprovision:
          - npm install
          - npm run cdk -- destroy --force --all
